<Script
  src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js"
  strategy="afterInteractive"
/>
<Script id="cookieconsent-init" strategy="afterInteractive">
  {`
    window.cookieconsent.initialise({
      palette: { popup: { background: "#000" }, button: { background: "#f1d600" } },
      theme: "classic",
      content: {
        message: "We use cookies to analyze traffic and show ads.",
        dismiss: "Got it!",
        link: "Learn more",
        href: "/privacy"
      }
    });
  `}
</Script>

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
